#%RAML 1.0
title: Issue tracker
mediaType: application/json
uses:
  core: coreLib.raml
types:
  Base:
    properties:
      id:
        type: integer
        (core.id):
      title: string
  Label:
    type: Base
    properties:
      color: string
  Project:
    type: Base
    properties:
      labels: Label[]
  Issue:
    type: Base
    properties:
      body: string
      labels:
        type: Label[]
        (core.reference): true
  Comment:
    type: Base
    properties:
      body: string
resourceTypes:
  collection:
    get:
      responses:
        200:
          body:
            properties:
               items: <<Type>>[]
               total: integer
    post:
      body: <<Type>>
      responses:
        200:
          body: <<Type>>

  item:
    uriParameters:
      id:
        (core.reference): <<Type>>.id
    put:
      body: <<Type>>
      responses:
        200:
          body: <<Type>>
    get:
      responses:
        200:
          body:
            <<Type>>
    delete:
       responses:
         200:
/projects:
  type:  { collection: {Type : Project} }
  /{id}:
    type:  { item: {Type : Project} }
    /labels:
      type: { collection: {Type : Label} }
      /{id}:
        type: { item: {Type : Label} }
    /issues:
      type: { collection: {Type : Issue} }
      /{id}:
        type:  { item: {Type : Issue} }
        /commments:
          type: { collection: {Type : Comment} }
          /{id}:
            type: { item: {Type : Comment} }
