#%RAML 1.0 Library
types:
  Person:
    properties:
      name:
        type: string
       
      lastName:
        type: string
       
  Manager:
    type: Person
    properties:
      manages:
        type: Person[]
        xml:
          wrapped: true
          name: person
