#%RAML 1.0 Library
types:
  TestTypeWithDefaults:
    properties:
      z:
        type: number
        format: float
        default: 2
      q:
        type: string
        default: "Hello"
      v:
        type: boolean
        default: true
