#%RAML 1.0 Library
types:
  CatOrDog: 
    type: Cat | Dog
    properties:
       fangs?: string
    
  HasKind:
    properties:
      kind: string
     
  Cat:
    type: HasKind
    properties:
      name: string
  Dog:
    type: HasKind
    properties:
      name: string
      price: number