#%RAML 1.0 Library
types:
  Base:
    properties:
      X: number
  HasY:
    properties:
      Y: number    
  Manager:
    properties:
      name: string
      innerType: 
        type: [ Base, HasY]
        properties: 
          qualityLevel: number

