#%RAML 1.0 Library
types:
  double:
    type: number
    format: double
  long:
    type: integer
    format: long
  ValidationBean:
    type: object
    properties:
      mm:
        type: long
        minimum: 1
        maximum: 3
      vv:
        type: double
        maximum: 3.0
        minimum: 2.0
      mmm:
        type: string | nil
        pattern: ..
      anotherString:
        type: string
        minLength: 8
        maxLength: 9
