#%RAML 1.0
title: APIMATIC API Transformer
version: '1.0'
baseUri: apitransformer.com/api
description: Transform API Descriptions from/to various formats
mediaType:
- application/json
- application/x-yaml
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
/transform:
  post:
    description: |-
      Transform API Descriptions from/to various formats e.g., Swagger, API Blueprint, RAML, WADL, Google Discovery, I/O Docs.

      ### INPUTS
      * API Blueprint
      * Swagger 1.0 - 1.2
      * Swagger 2.0 JSON
      * Swagger 2.0 YAML
      * WADL - W3C 2009
      * Google Discovery
      * RAML 0.8
      * I/O Docs - Mashery
      * HAR 1.2
      * Postman Collection 1.0
      * APIMATIC Format
      * Mashape

      ### OUTPUTS
      * API Blueprint
      * Swagger 1.2
      * Swagger 2.0 JSON
      * Swagger 2.0 YAML
      * WADL - W3C 2009
      * RAML 0.8
      * APIMATIC Format
    displayName: Transform API Descriptions from/to various formats
    queryParameters:
      output:
        type: string
        displayName: output
        enum:
        - swagger12
        - swagger20json
        - swagger20yaml
        - apiblueprint
        - wadl
        - raml08
        - apimatic
    responses:
      200:
        description: The converted API specification
        body:
          application/json:
            type: object
          application/x-yaml:
            type: object
      429:
        description: Rate-limit exceeded
