#%RAML 1.0 Overlay
extends: apigateway.raml
uses:
  AWS: apigateway-lib.raml
/products:
  get:
    (AWS.amazon-apigateway-integration):
      type: aws
      uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:393636047515:function:MyFunction/invocations"
      httpMethod: POST
      credentials: "arn:aws:iam::393636047515:role/lambda_exec_role"
      requestTemplates:
        application/json: "json request template 2"
        application/xml: "xml request template 2"
      requestParameters:
          integration.request.path.integrationPathParam: "method.request.querystring.latitude"
          integration.request.querystring.integrationQueryParam: "method.request.querystring.longitude"
      cacheNamespace: "cache namespace"
      cacheKeyParameters: []
      responses:
          "200":
            statusCode: "200"
            responseTemplates:
              application/json: "Hello World"
              application/xml: "xml 200 response template"
          "400":
            statusCode: "400"
            responseTemplates:
              application/json: "json 400 response template"
              application/xml: "xml 400 response template"
