#%RAML 1.0 Library
annotationTypes:
  Hidden:
    type: nil
  FieldConfig:
    type: object
    properties:
      order: int
      caption: string
types:
  VehicleKind:
    type: string
    enum:
    - MILITARY
    - CARGO
    - PEOPLE
  double:
    type: number
    format: double
  int:
    type: integer
    format: int
  Vehicle:
    type: object
    properties:
      name:
        type: string
        (FieldConfig):
          order: 1
          caption: Name of vehicle
      speed:
        type: double
        (FieldConfig):
          order: 2
          caption: Maximum Speed of vehicle
      kind:
        type: VehicleKind
        (Hidden):
  Aircraft:
    type: Vehicle
    properties:
      ceiling: number
  Submarine:
    type: Vehicle
    properties:
      maxDive: number
  Boat:
    type: Vehicle
    properties:
      sizeClass: integer
  SeaVehicle: Boat | Submarine
  PricedItem:
    properties:
      price: number
  BoatForSale: [Boat, PricedItem]
  VehiclesAtLocation:
    properties:
      location: string
      vehicles: Vehicle[]