#%RAML 1.0
baseUri: http://example.org/dd
title: Hello
protocols: [HTTP]
types:
  Person:
    properties:
      name: string
      lastName: string
      age?: number
  PersonArray: Person[]
  PersonArray2: 
    type: PersonArray
    minItems: 2
