#%RAML 1.0
title: Hello
securitySchemes:
    oath2:
       type: OAuth 2.0
       settings:
         accessTokenUri: http
         authorizationUri: dd
         authorizationGrants: password
         scopes: [a,b]
/g:
  get:
    securedBy:
        oath2:
         scopes: [ a ]
