package org.aml.typesystem.raml.model;

import java.util.List;

import org.aml.typesystem.AbstractType;
import org.raml.v2.api.model.v10.security.SecuritySchemeRef;


public interface Resource extends Annotable{

    /**
     * Relative URL of this resource from the parent resource
     **/
    String relativeUri();


    /**
     * The displayName attribute specifies the resource display name. It is a friendly name used only for  display or documentation purposes. If displayName is not specified, it defaults to the element's key (the name of the property itself).
     **/
    String displayName();


    /**
     * A nested resource is identified as any property whose name begins with a slash ("&#47;") and is therefore treated as a relative URI.
     **/
    List<Resource> resources();


    /*
     * helper methods (non-autogenerated)
     */

    String resourcePath();
    
    Resource parentResource();
    
    /**
     * Methods that are part of this resource type definition
     **/
    List<Method> methods();


    // --def-system-mod--
    String description();


    /**
     * The security schemes that apply to all methods declared (implicitly or explicitly) for this resource.
     **/
    List<SecuritySchemeRef> securedBy();


    /**
     * Detailed information about any URI parameters of this resource
     **/
    List<AbstractType> uriParameters();

}