#%RAML 1.0
title: Hello
securitySchemes:
   oath:
     type: OAuth 2.0
     settings:
       accessTokenUri: http
       authorizationUri: dd
       authorizationGrants: password
/g:
  get:
    securedBy:
      oath:
        scopes: [c]
